
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Oct  2 2025 15:03:22 -03 (Oct  2 2025 18:03:22 UTC)

// Verification Directory fv/multiplexor 

module multiplexor(in0, in1, sel, mux_out);
  input [4:0] in0, in1;
  input sel;
  output [4:0] mux_out;
  wire [4:0] in0, in1;
  wire sel;
  wire [4:0] mux_out;
  sg13g2_mux2_1 g136__2398(.A0 (in0[4]), .A1 (in1[4]), .S (sel), .X
       (mux_out[4]));
  sg13g2_mux2_1 g140__5107(.A0 (in0[2]), .A1 (in1[2]), .S (sel), .X
       (mux_out[2]));
  sg13g2_mux2_1 g137__6260(.A0 (in0[1]), .A1 (in1[1]), .S (sel), .X
       (mux_out[1]));
  sg13g2_mux2_1 g138__4319(.A0 (in0[0]), .A1 (in1[0]), .S (sel), .X
       (mux_out[0]));
  sg13g2_mux2_1 g139__8428(.A0 (in0[3]), .A1 (in1[3]), .S (sel), .X
       (mux_out[3]));
endmodule

